### ISSUE TITLE
release date

### ISSUE THREAD

**Issue by nmll** [roscenes/RoScenes#1]
Excellent work! When will the dataset be released?

**Comment by roscenes** [comment]
Hi nmll,

Sorry for the inconvenience. Now, we are releasing the dataset at [ModelScope](https://modelscope.cn/datasets/Apsara_Lab_Multimodal_Intelligence/RoScenes-release). Please check the newest link in the `README.md` for downloading.

**Comment by xiaosu-zhu** [comment]
Closed due to inactivity. If you have any other questions, you could re-open it or file a new issue. Thanks for your attention!
