### ISSUE TITLE
Cannot download dataset because of no authority

### ISSUE THREAD

**Issue by WendellGong** [roscenes/RoScenes#2]
How to download from modelscope?
![image](https://github.com/user-attachments/assets/16ddc87b-3e07-4f3a-93c6-876c5bb6d137)

**Comment by roscenes** [comment]
Hi, WendellGong,

Sorry for the inconvenience. We have update the link of dataset due to a previous uploading error. Please check the newest link in the `README.md` for downloading.

**Comment by WendellGong** [comment]
Oh, I see, thx!
