### ISSUE TITLE
eval toolkit

### ISSUE THREAD

**Issue by InnovationMatrix** [roscenes/RoScenes#3]
你好！这个数据集有评测方式么？有发布计划么？有的话预计什么时候

**Comment by xiaosu-zhu** [comment]
Hi @InnovationMatrix 

Thanks for your attention to this project. Sorry for the delay.

We have provide examples and evaluation guide for training and evaluation. Please refer to [examples/mmdet3d/mmdet3d_plugin/datasets/roscenes_dataset.py](https://github.com/roscenes/RoScenes/blob/main/examples/mmdet3d/mmdet3d_plugin/datasets/roscenes_dataset.py) and [roscenes/evaluation/README.md](https://github.com/roscenes/RoScenes/blob/main/roscenes/evaluation/README.md) for the information.

**Comment by xiaosu-zhu** [comment]
Closed due to inactivity. If you have any other questions, you could re-open it or file a new issue. Thanks for your attention!
