### ISSUE TITLE
So sad, two months are gone, but there is no available codes for training or validation.

### ISSUE THREAD

**Issue by WangzcBruce** [roscenes/RoScenes#4]
Looking forward to the open-sourced toolkits!

**Comment by xiaosu-zhu** [comment]
Hi @WangzcBruce 

Thanks for your attention to this project. Sorry for the delay.

We have provide examples and evaluation guide for training and evaluation. Please refer to [`examples/mmdet3d/mmdet3d_plugin/datasets/roscenes_dataset.py`](https://github.com/roscenes/RoScenes/blob/main/examples/mmdet3d/mmdet3d_plugin/datasets/roscenes_dataset.py) and [`roscenes/evaluation/README.md`](https://github.com/roscenes/RoScenes/blob/main/roscenes/evaluation/README.md) for the information.

**Comment by xiaosu-zhu** [comment]
Closed due to inactivity. If you have any other questions, you could re-open it or file a new issue. Thanks for your attention!
